### ISSUE TITLE
关于macOS挂载后目录为空

### ISSUE THREAD

**Issue by howie6879** [messense/aliyundrive-fuse#1]
Hi @messense ，感谢你的项目，我按照README操作后，终端输出如下：

```shell
(base) ➜  ~ sudo aliyundrive-fuse -r token -w /var/run/aliyundrive /mnt/aliyundrive
2022-01-10T01:29:19.838490Z  INFO aliyundrive_fuse::drive: refresh token succeed refresh_token=token nick_name=howie6879
2022-01-10T01:29:19.839350Z  INFO aliyundrive_fuse::drive: found default drive drive_id=87925441
```

但是`aliyundrive`下内容为空，是我使用方式不对吗？

![image](https://user-images.githubusercontent.com/17047388/148709487-58e6366a-0ee8-4ba3-82b1-fe09463ed11a.png)

系统版本：10.13.6

**Comment by messense** [comment]
没在这么低版本 macOS 上试过，可以开启 debug 日志跑看看，设置环境变量 `RUST_LOG=aliyundrive_fuse=debug`，然后直接 shell 里面 `ls /mnt/aliyundrive`

**Comment by howie6879** [comment]
找到原因了，操作目录/mnt/aliyundrive这边权限都是sudo，尝试了下在当前用户目录下新建目录进行操作，就没问题了，谢谢
