### ISSUE TITLE
催更，看到docker镜像了，求列出用法

### ISSUE THREAD

**Issue by fusang1337** [messense/aliyundrive-fuse#10]
尝试配置了环境变量之类的 报错了

Error: fusermount3: fuse device not found, try 'modprobe fuse' first

**Comment by messense** [comment]
需要 `--privileged` 和 `--device /dev/fuse:/dev/fuse`

**Comment by fusang1337** [comment]
## 群晖设备使用报错
### 第一步：拉取 [aliyundrive-fuse]
`docker pull messense/aliyundrive-fuse:sha-2e8dcbf`
### web管理，控制面板，计划任务，开机执行，挂载你需要的映射的卷
`mount --make-shared /volume1`
### web管理，filestation，新增共享文件夹，在你映射的卷上（我的是/volume1/aliyun）
### 创建Docker
`docker run --name=aliyundrive-fuse \
--privileged \
--device /dev/fuse:/dev/fuse \
--restart unless-stopped \
-v /volume1/aliyun:/volume1/aliyun \
-v /volume1/docker/aliyun-fuse:/volume1/docker/aliyun-fuse \
-e TZ=Asia/Shanghai \
-e REFRESH_TOKEN=4a2fdb956cdc44f19f88577597467cc8 \
-e PATH=/volume1/aliyun \
-e WORKDIR=/volume1/docker/aliyun-fuse \
messense/aliyundrive-fuse:sha-2e8dcbf`

报错
`2022-02-09T01:33:35.536454Z  INFO aliyundrive_fuse::drive: refresh token succeed refresh_token=5cc8b322c06b4954a44a8246764b2fca nick_name=扶桑1337
2022-02-09T01:33:35.536770Z  INFO aliyundrive_fuse::drive: found default drive drive_id=2230535
Error: No such file or directory (os error 2)`

不晓得找不到那个文件啊 =-= 尝试过更改PATH,path,WORKDIR,worddir环境变量都不行

**Comment by messense** [comment]
目前 dockerfile 里面配置的挂载目录是 `/mnt/aliyundrive`.

https://github.com/messense/aliyundrive-fuse/blob/2e8dcbf49b00533499daf53aa431bedebecd58bc/Dockerfile#L15

**Comment by messense** [comment]
你也可以重新指定 CMD

```
docker run --name=aliyundrive-fuse \
--privileged \
--device /dev/fuse:/dev/fuse \
--restart unless-stopped \
-v /volume1/aliyun:/volume1/aliyun:shared \
-v /volume1/docker/aliyun-fuse:/volume1/docker/aliyun-fuse \
-e TZ=Asia/Shanghai \
-e REFRESH_TOKEN=xxxx \
messense/aliyundrive-fuse:sha-2e8dcbf
/usr/bin/aliyundrive-fuse --workdir /volume1/docker/aliyun-fuse  /volume1/aliyun
```

**Comment by fusang1337** [comment]
谢谢！！！

**Comment by messense** [comment]
> UNRAID用户，试了一天了，日志不报错，就是找不到那个文件。unraid的docker镜像是保存在docker.img里面，实在是整不会了。前来求教。

@leec0830 没用过 UNRAID 没法帮你。

**Comment by hanley520** [comment]
您好开发者，
2022-05-26T14:17:40.286514Z  INFO aliyundrive_fuse::drive: refresh token succeed refresh_token=xxx nick_name=hanley
2022-05-26T14:17:40.287663Z  INFO aliyundrive_fuse::drive: found default drive drive_id=6317844
 但是在群晖文件夹加载不出来

**Comment by irockstar** [comment]
> 您好开发者，
> 2022-05-26T14:17:40.286514Z INFO aliyundrive_fuse::drive: refresh token succeed refresh_token=xxx nick_name=hanley
> 2022-05-26T14:17:40.287663Z INFO aliyundrive_fuse::drive: found default drive drive_id=6317844
> 但是在群晖文件夹加载不出来

遇到同样问题

![WX20220727-175155](https://user-images.githubusercontent.com/1676743/181218571-f3b83141-7941-47ca-b09b-614a2e99d291.png)

![WX20220727-175128](https://user-images.githubusercontent.com/1676743/181218603-262f97c5-2663-4ad7-90ad-acd736423ddc.png)
