### ISSUE TITLE
阿里云盘 FUSE，访问速度太慢

### ISSUE THREAD

**Issue by jy3344511** [messense/aliyundrive-fuse#12]
网络下载速度能达到50M/s，先使用的aliyundrive-webdav，用PotPlayer进行播放的话，速度稳定在20几M/s的样子，拖动进度条快进的话，基本不卡。但是，平时用Jellyfin，所以又转到aliyundrive-fuse。用fuse的话，播放速度最多只有10M/s出头的样子，拖动进度条观看的话，就会卡很长时间了。

希望fuse挂载阿里云盘，能增加写的功能，整理阿里云盘时，经常要用到批量重命名的功能，复制、移动、删除等操作，也很频繁。

**Comment by zaizhuzhu123** [comment]
确实目前使用 aliyundrive-webdav+rclone 方案更流畅一些
可能fuse还需要进一步优化吧

**Comment by xcf13363175** [comment]
一样的情况，速度10M/s，而webdav满速。

**Comment by taocwang** [comment]
> 确实目前使用 aliyundrive-webdav+rclone 方案更流畅一些 可能fuse还需要进一步优化吧

我的实测结果是aliyundrive-webdav很快，加上rclone很慢，fuse快于rclone

**Comment by taocwang** [comment]
我的实测结果是aliyundrive-webdav很快，加上rclone很慢，aliyundrive-fuse快于rclone。

但是fuse出现丢失文件的情况，文件本身有51个，aliyundrive-webdav访问正常，可是用aliyundrive-fuse就会出现只有50个的情况，希望大神解决，谢谢！
