### ISSUE TITLE
emby 无法访问文件夹

### ISSUE THREAD

**Issue by KimmyLueng** [messense/aliyundrive-fuse#14]
按教程在 vps 里设置加载好阿里云盘。能查看云盘里的东西，但 emby 没有权限读取/mnt/aliyundrive文件夹。还要怎样设置

**Comment by shuax** [comment]
我也是，文件夹已经映射进去了，但是emby选择的时候没有。

**Comment by shuax** [comment]
我把emby的gid和uid改成了0可以访问了。

**Comment by jnlpc123** [comment]
> 我把emby的gid和uid改成了0可以访问了。

求教群晖套件版emby如何修改

**Comment by shuax** [comment]
> > 我把emby的gid和uid改成了0可以访问了。
> 
> 求教群晖套件版emby如何修改

我后面是把aliyundrive-fuse加了运行参数--allow-other

**Comment by spirytuslove** [comment]
> > > 我把emby的gid和uid改成了0可以访问了。
> > 
> > 
> > 求教群晖套件版emby如何修改
> 
> 我后面是把aliyundrive-fuse加了运行参数--allow-other
问下docker下aliyundrive-fuse怎么加运行参数--allow-other啊现在plex不能选择挂载的盘
