### ISSUE TITLE
挂载目录权限问题

### ISSUE THREAD

**Issue by adminpass** [messense/aliyundrive-fuse#2]
### 环境

群辉（X86），fusermount3（移植自rpm包），用户（root，admin，plex）

### 现象

- 使用**root**执行挂载，群辉admin用户访问正常，但plex用户访问不了

- 使用**admin**执行挂载，目录出现权限异常（ls: cannot access 阿里云盘: Permission denied）

![11111111](https://user-images.githubusercontent.com/7523220/148896635-85dcd7e7-43bc-44cd-bbf2-cce02ef93ca5.jpg)
![22222222](https://user-images.githubusercontent.com/7523220/148896649-48443135-c598-490e-9477-39e2d1c9e7e0.jpg)

### 问题

1. 是否支持非root用户挂载
2. 挂载后其它用户访问权限设置

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-fuse/suites/4893776690/artifacts/140398308

试试用这个增加 `--allow-other` 参数运行。

**Comment by adminpass** [comment]
> https://github.com/messense/aliyundrive-fuse/suites/4893776690/artifacts/140398308
> 
> 尝试使用这个增加的`--allow-other`参数运行。

可以，谢了

**Comment by shinobiz** [comment]
完了，看不懂。已经linux命令到了该文件夹，和楼主一样发现权限都是？？？？，但就是搞不定。。。。

**Comment by shinobiz** [comment]
> https://github.com/messense/aliyundrive-fuse/suites/4893776690/artifacts/140398308
> 
> 试试用这个增加 `--allow-other` 参数运行。
完了，看不懂。已经linux命令到了该文件夹，和楼主一样发现权限都是？？？？，但就是搞不定。。。。
点击了链接还是回到这一页

**Comment by shinobiz** [comment]
测试了下，关闭“阿里云fuse”套件，文件夹可以进入，且命令到目录查看权限正常，一旦运行套件，目录权限就变成？？？？？

大佬能否更新一下套件
