### ISSUE TITLE
报错 error sending request for url (https://websv.aliyundrive.com/token/refresh)

### ISSUE THREAD

**Issue by BaiBaiAi** [messense/aliyundrive-fuse#21]
WARN aliyundrive_fuse::drive: refresh token failed, will wait and retry error=error sending request for url (https://websv.aliyundrive.com/token/refresh): error trying to connect: dns error: failed to lookup address information: Try again
但是实际DNS是没问题的
ping -a websv.aliyundrive.com
PING websv.aliyundrive.com (101.200.125.2) 56(84) bytes of data.
64 bytes from 101.200.125.2: icmp_seq=1 ttl=91 time=50.2 ms
64 bytes from 101.200.125.2: icmp_seq=2 ttl=91 time=58.3 ms
64 bytes from 101.200.125.2: icmp_seq=3 ttl=91 time=131 ms
64 bytes from 101.200.125.2: icmp_seq=4 ttl=91 time=59.2 ms
64 bytes from 101.200.125.2: icmp_seq=5 ttl=91 time=60.8 ms
64 bytes from 101.200.125.2: icmp_seq=6 ttl=91 time=52.6 ms
64 bytes from 101.200.125.2: icmp_seq=7 ttl=91 time=59.8 ms
^C
--- websv.aliyundrive.com ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6010ms
rtt min/avg/max/mdev = 50.228/67.470/131.130/26.250 ms

**Comment by messense** [comment]
参考：https://github.com/messense/aliyundrive-fuse/issues/15#issuecomment-1048631863

**Comment by BaiBaiAi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by BaiBaiAi** [comment]
> 参考：[#15 （评论）](https://github.com/messense/aliyundrive-fuse/issues/15#issuecomment-1048631863)

谢谢  另外能否更新下docker部署的方法   dockerhub 和github上都没看到部署命令 @messense

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-fuse/issues/10
