### ISSUE TITLE
docker方式运行挂载的云盘目录能不能映射给宿主机

### ISSUE THREAD

**Issue by hui9464** [messense/aliyundrive-fuse#22]
使用docker方式运行挂载的云盘目录，进去容器里面也能查看到阿里云盘的内容。通过docker run -v方式映射目录，但是宿主机的目录下，里面为空。能不能把docker内已挂载的阿里云盘目录映射给宿主机目录？

**Comment by messense** [comment]
https://stackoverflow.com/a/53632103
