### ISSUE TITLE
请问下，plex挂载不了AliyunDrive文件，不可选。怎么修改？ 

### ISSUE THREAD

**Issue by ego8898** [messense/aliyundrive-fuse#25]

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-fuse/issues/14#issuecomment-1079907694

**Comment by spirytuslove** [comment]
问下你最后怎么解决的 我docker安装的aliyundrivefuse也遇到相同问题

**Comment by yyqyu** [comment]
我知道二进制跑的时候加上allow other 就好了
