### ISSUE TITLE
请问作者R4S用啥固件，核显硬解

### ISSUE THREAD

**Issue by zf1976** [messense/aliyundrive-fuse#28]
请问作者这种情况正常吗，jellyfin挂载后扫描占用起飞
![image](https://user-images.githubusercontent.com/51810656/161684518-49e51f4b-c24b-4e77-9e6f-e4506488ffd0.png)

![image](https://user-images.githubusercontent.com/51810656/161684424-d4f34bfa-3b21-45e1-8c25-2877f4b5f53d.png)

**Comment by messense** [comment]
https://github.com/kiddin9/OpenWrt_x86-r2s-r4s

没在 OpenWrt 上跑 Jellyfin，跑在 NUC 8 上.
