### ISSUE TITLE
挂载到OpenWRT的外接硬盘目录下文件不显示

### ISSUE THREAD

**Issue by showlee** [messense/aliyundrive-fuse#30]
下载OpenWRT相关的FUSE插件安装后，并根据文档方法及命令，将云盘挂载到了/mnt/sdb2(OpenWRT外接的硬盘的第二分区)，刚开始看到是挂在成功了的，也要显示云盘里的目录和文件，但是再一刷新就只看得到挂载的云盘目录，而点击进去就再没有看到目录和文件啦。这是怎么回事呢？盼解答，谢谢！

**Comment by messense** [comment]
不需要挂载到硬盘，只需要是个空目录。

**Comment by showlee** [comment]
又测试啦，只能挂载一个阿里云盘的Torken么？
