### ISSUE TITLE
请问提示错误fusermount怎么解决

### ISSUE THREAD

**Issue by howecheung** [messense/aliyundrive-fuse#32]
Error: fusermount: fuse device not found, try 'modprobe fuse' first

**Comment by messense** [comment]
系统问题请自行搜索解决。

**Comment by zuohuadong** [comment]
@messense 
> 系统问题请自行搜索解决。

messense/aliyundrive-fuse:latest
    
使用 docker 镜像跑就会报这个错，应该跟 容器下  rclone 挂载有关。
