### ISSUE TITLE
群晖docker无法使用

### ISSUE THREAD

**Issue by wanghaihua** [messense/aliyundrive-fuse#33]
可以运行，但是目录上没有映射文件，不知道是什么地方过的问题

**Comment by messense** [comment]
请提供详细复现步骤。

**Comment by wanghaihua** [comment]
用的群晖你的官方源，设置好了refresh_token，群晖docker管理装载路径设置的/mnt/aliyundrive。WORKDIR设置其他挂载路径不起作用。可能是docker里面没有mnt这个路径吧

**Comment by messense** [comment]
参考 https://github.com/messense/aliyundrive-fuse/issues/10
