### ISSUE TITLE
请教一下，群晖挂在后，为什么只有admin用户组才能访问

### ISSUE THREAD

**Issue by shinobiz** [messense/aliyundrive-fuse#36]
users用户组内的用户即便给了文件夹权限，也无法访问，还是提示权限不足

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-fuse/issues/2#issuecomment-1009672552

**Comment by shinobiz** [comment]
测试了下，关闭“阿里云fuse”套件，文件夹可以进入，且命令到目录查看权限正常，一旦运行套件，目录权限就变成？？？？？

大佬能否更新一下套件
