### ISSUE TITLE
openwrt x86 无法使用

### ISSUE THREAD

**Issue by touzi** [messense/aliyundrive-fuse#4]
openwrt 安装完成, 并且配置成功后, 使用 Emby 或者 Jellyfin 都无法连接上. 

openwrt 已经安装并且能够正常使用 aliyundrive-webdav .

**Comment by messense** [comment]
详细说一下你怎么配置的。

**Comment by touzi** [comment]
安装完成后填写了 Refresh Token, 然后启动.

**Comment by messense** [comment]
我的意思是你怎么配置 Emby/Jellyfin 来使用挂载的磁盘的。

**Comment by touzi** [comment]
我大概懂了, Emby/Jellyfin 都需要在 openwrt 上重新架设系统使用. 

我以为和 aliyundrive-webdav 直接输入内网IP 就可以使用.
