### ISSUE TITLE
请教 jellyfin 安装在windows server，aliyundrive安装在N1上

### ISSUE THREAD

**Issue by greedisgoood** [messense/aliyundrive-fuse#48]
请教 jellyfin 安装在windows server，aliyundrive安装在N1上，windows 可以smba共享 jellyfin不能读取。请教设置方法。

**Comment by zhuzhe1983** [comment]
都有windows server了，为什么不用webdav在windows上mount？

**Comment by messense** [comment]
非本项目问题
