### ISSUE TITLE
预编译 Release 请求添加 mipsel 和 mips 架构，大量路由器在用这个架构。

### ISSUE THREAD

**Issue by blickers** [messense/aliyundrive-fuse#50]
目前有 arm 的，有 x86 的，唯独没有 mipsel 的，请求添加 mips 和 mipsel ，大量的路由器在用则个架构，例如 MT7620/7621/7628。

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-fuse/releases/tag/v0.1.12
