### ISSUE TITLE
docker安装

### ISSUE THREAD

**Issue by seed330** [messense/aliyundrive-fuse#51]
docker composs

 -v  /mnt/user/appdata/aliyun/ /var/run/aliyundrive-fuse
-e REFRESH_TOKEN *************

*****
[2m2022-05-25T02:09:53.679405Z[0m [32m INFO[0m [2maliyundrive_fuse::drive[0m[2m:[0m found default drive [3mdrive_id[0m[2m=[0m1926120
Error: fusermount3: fuse device not found, try 'modprobe fuse' first

docker停止了

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-fuse/issues/10
