### ISSUE TITLE
路径，文件名的中文字符能否采用utf8

### ISSUE THREAD

**Issue by zjy760401** [messense/aliyundrive-fuse#52]
我在使用aliyundrive-fuse 映射文件时候在PLEX中文件名称为乱码，
该现象类似我在mount时候没有指定iocharset=utf8时候出现的现象。
想请问能否添加类似功能，使文件，路径的字符集支持UTF8，
感谢！

**Comment by adminpass** [comment]
检查系统字符集、PLEX配置，目前在用未出现乱码问题
