### ISSUE TITLE
求助：illegal hardware instruction  aliyundrive-fuse -h

### ISSUE THREAD

**Issue by ccbcfan** [messense/aliyundrive-fuse#55]
我家云armbian系统，docker中安装了openwrt，想在op中安装aliyundrive-fuse。
`$ opkg print-architecture
arch all 1
arch noarch 1
arch arm_cortex-a7_neon-vfpv4 10
`
`$ opkg install aliyundrive-fuse_0.1.12-1_arm_cortex-a7_neon-vfpv4.ipk
Package aliyundrive-fuse (0.1.12-1) installed in root is up to date.
`
$ aliyundrive-fuse -h
[1]    21028 illegal hardware instruction  aliyundrive-fuse -h
``

**Comment by messense** [comment]
`cat /proc/cpuinfo` 看看，感觉是 CPU 太老了。
