### ISSUE TITLE
debian系统上显示了挂载的阿里盘,但是emby设置媒体文件夹的时候没有访问挂载盘的权限,该怎么设置

### ISSUE THREAD

**Issue by coder2008** [messense/aliyundrive-fuse#59]
debian系统上显示了挂载的阿里盘,但是emby设置媒体文件夹的时候没有访问挂载盘的权限,该怎么设置

**Comment by messense** [comment]
https://github.com/messense/aliyundrive-fuse/issues/14#issuecomment-1079907694
