### ISSUE TITLE
Refresh token failed

### ISSUE THREAD

**Issue by VectorZhao** [messense/aliyundrive-fuse#62]
**运行环境：**
甲骨文，arm，新加坡

抓到token之后，运行挂载命令，提示错误如下
`2022-06-28T06:47:58.646900Z  WARN aliyundrive_fuse::drive: refresh token failed, will wait and retry error=error sending request for url (https://websv.aliyundrive.com/token/refresh): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution`
`ping websv.aliyundrive.com` 是可以`ping`通的，
请问是不是该VPS限制了阿里云的什么？
上述问题能否得到解决？

**Comment by messense** [comment]
不知道，网络环境问题自行排查。
