### ISSUE TITLE
挂载问题

### ISSUE THREAD

**Issue by spirytuslove** [messense/aliyundrive-fuse#65]
大佬请教下docker下安装的aliyundrive-fuse挂载成功 但是docker下的plex添加不了媒体库 但是同样配置docker下的emby就能添加媒体库 又尝试了下docker安装clouddrive挂载 然后再到docker下plex能添加clouddrive挂载的媒体文件 请教下怎么才能在docker plex中添加aliyundrive-fuse挂载的媒体文件啊。。。

**Comment by messense** [comment]
没用过 plex 不知道。
