### ISSUE TITLE
大佬这个问题怎么解决啊

### ISSUE THREAD

**Issue by hackerlengyue** [messense/aliyundrive-fuse#7]
所有都按照步骤弄，最后这个
-bash: aliyundrive-fuse: command not found

请求大佬解答下，我是小白已经研究一天了

**Comment by messense** [comment]
哪个步骤？

**Comment by hackerlengyue** [comment]
最后添加token时候，目前我换了一个系统添加成功了，最后还是有报错os error2

**Comment by hackerlengyue** [comment]
求大佬出个centos的视频教程，也可能我用的镜像问题，各种奇奇怪怪的问题

**Comment by messense** [comment]
请给出详细的步骤和报错信息，否则无法判断、没法帮你。

**Comment by hackerlengyue** [comment]
老哥解决了，谢谢老哥
