### ISSUE TITLE
求助：OpenWrt上fuse启动报错

### ISSUE THREAD

**Issue by DeadpoolRain** [messense/aliyundrive-fuse#70]
OpenWrt上fuse启动不了。使用相同的Refresh Token，WebDAV却可以正常使用。
aliyundrive-fuse 0.1.14 未运行
日志：
ERROR aliyundrive_fuse::drive: refresh token failed: HTTP status client error (400 Bad Request) for url (https://api.aliyundrive.com/token/refresh): {"code":"InvalidParameter.ClientId","message":"The input parameter client_id is not valid. ","requestId":null}
Error: initialize aliyundrive client failed

我用的是R4s，刷的骷髅头的固件，固件版本是OpenWrt R22.3.13 (2022-07-14) / LuCI Master (git-22.190.06436-4a8cc2a)，内核版本是5.4.187。

**Comment by messense** [comment]
该项目暂时只支持 web 版 refresh_token.

**Comment by DeadpoolRain** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DeadpoolRain** [comment]
问题已解决！谢谢！
