### ISSUE TITLE
docker fuse volumes 无法与 emby 共享

### ISSUE THREAD

**Issue by irockstar** [messense/aliyundrive-fuse#71]
docker-compose 不使用 shared 参数，进入 aliyundrive-fuse 容器内部可以看到阿里云盘文件，但在宿主机 /mnt/aliyunpan 中没有内容

![WX20220728-103708](https://user-images.githubusercontent.com/1676743/181408179-babe4291-fd96-4778-84a7-8edf5f615943.png)

如果使用 shared 参数，宿主机 /mnt/aliyunpan 权限变成 【？？？】并且无法访问

![WX20220728-102323](https://user-images.githubusercontent.com/1676743/181408325-0312d791-c2b4-4be4-8967-3f738a7199d2.png)

![WX20220728-102420](https://user-images.githubusercontent.com/1676743/181408399-865d07b5-015b-43bb-92b5-8f6ff39f4a4c.png)

请教！感谢分享！

**Comment by messense** [comment]
`--allow-other`.

**Comment by irockstar** [comment]
请问这样写可以覆盖 Dockerfile 中的CMD 吗？

![image](https://user-images.githubusercontent.com/1676743/181412959-d4ad6f85-7345-4676-9133-072f674f11aa.png)

**Comment by irockstar** [comment]
搞定了！

![image](https://user-images.githubusercontent.com/1676743/181414020-6ce5fcad-1c8f-4ed7-baaf-e9596eec5437.png)

感谢
