### ISSUE TITLE
谢谢大佬付出，群晖如何搭建？

### ISSUE THREAD

**Issue by fusang1337** [messense/aliyundrive-fuse#8]

**Comment by fusang1337** [comment]
我尝试了pip3 install aliyundrive-fuse可以安装aliyundrive_fuse-0.1.5-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl
但是安装之后输入aliyundrive-fuse
报错-ash: aliyundrive-fuse: command not found

而apt或者yum都报错
root@nas:~# apt-get install -y fuse3
-ash: apt-get: command not found

root@nas:~# yum install -y fuse3
-ash: yum: command not found

**Comment by fusang1337** [comment]
`fusang@nas:/$ apt-get install -y fuse3
-sh: apt-get: command not found
fusang@nas:/$ sudo -i
Password:
root@nas:~#
root@nas:~#
root@nas:~# apt-get install -y fuse3
-ash: apt-get: command not found
root@nas:~#
root@nas:~# yum install -y fuse3
-ash: yum: command not found
root@nas:~#
root@nas:~#
root@nas:~# pip install aliyundrive-fuse
-ash: pip: command not found
root@nas:~# pip3 install aliyundrive-fuse
Collecting aliyundrive-fuse
  Downloading aliyundrive_fuse-0.1.5-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 124 kB/s
Installing collected packages: aliyundrive-fuse
Successfully installed aliyundrive-fuse-0.1.5
root@nas:~# aliyundrive-fuse
-ash: aliyundrive-fuse: command not found
root@nas:~#
root@nas:~# aliyundrive-fuse
-ash: aliyundrive-fuse: command not found
root@nas:~#
root@nas:~# pip3 aliyundrive-fuse
ERROR: unknown command "aliyundrive-fuse"`

**Comment by fusang1337** [comment]
> fusang@nas:/$ apt-get install -y fuse3
-sh: apt-get: command not found
fusang@nas:/$ sudo -i
Password:
root@nas:~#
root@nas:~#
root@nas:~# apt-get install -y fuse3
-ash: apt-get: command not found
root@nas:~#
root@nas:~# yum install -y fuse3
-ash: yum: command not found
root@nas:~#
root@nas:~#
root@nas:~# pip install aliyundrive-fuse
-ash: pip: command not found
root@nas:~# pip3 install aliyundrive-fuse
Collecting aliyundrive-fuse
  Downloading aliyundrive_fuse-0.1.5-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 124 kB/s
Installing collected packages: aliyundrive-fuse
Successfully installed aliyundrive-fuse-0.1.5
root@nas:~# aliyundrive-fuse
-ash: aliyundrive-fuse: command not found
root@nas:~#
root@nas:~# aliyundrive-fuse
-ash: aliyundrive-fuse: command not found
root@nas:~#
root@nas:~# pip3 aliyundrive-fuse
ERROR: unknown command "aliyundrive-fuse"

**Comment by messense** [comment]
没有群晖，你可以请教下 @adminpass https://github.com/messense/aliyundrive-fuse/issues/2

**Comment by adminpass** [comment]
**1.Releases下载对应版本** 

**x86_64:** aliyundrive-fuse-v0.1.5.x86_64-unknown-linux-musl.tar.gz
**Arm:** aliyundrive-fuse-v0.1.5.arm-unknown-linux-musleabi.tar.gz（v7类型U：aliyundrive-fuse-v0.1.5.armv7-unknown-linux-musleabi.tar.gz）

**2.解压，拿到 aliyundrive-fuse**

**3. 上传群辉目录，chmod改执行权限，为避免麻烦，root下执行：**

./aliyundrive-fuse -r **refresh_token**  -w /var/run/aliyundrive-fuse /volume3/video/阿里云盘/ --allow-other

其中 **/volume3/video/阿里云盘/** 为你想挂载的地址

后台运行，nohup 或者用控制面板->任务计划->新建

**Comment by messense** [comment]
Thank you @adminpass

**Comment by fusang1337** [comment]
谢谢！ @adminpass
