### ISSUE TITLE
有的文件莫名奇妙地显示不出

### ISSUE THREAD

**Issue by TTomDuan** [messense/aliyundrive-fuse#80]
如有一个音频
"郎朗 - Piano Concerto No.2 in C Minor, Op. 18 - Piano Concerto No.2 In C Minor, Op.18 - 3. Allegro scherzando (C小调第2号钢琴协奏曲，作品18 - 第三乐章：诙谐的快板).flac"
挂载云盘后再在文件夹中`ls`，其他文件都有，独这个不显示，但重命名在后面加上个1，就又能显示了，改回来又不行，很奇怪。然后其他文件有时也遇到类似的问题，感觉应该不是命名的问题。

**Comment by messense** [comment]
Duplicate of #76
